# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 20, 400, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.emailerror = QtWidgets.QLabel(Form)
        self.emailerror.setGeometry(QtCore.QRect(100, 100, 261, 25))
        self.emailerror.setObjectName("emailerror")
        self.pswderror = QtWidgets.QLabel(Form)
        self.pswderror.setGeometry(QtCore.QRect(400, 100, 261, 25))
        self.pswderror.setObjectName("pswderror")
        self.emailerror_2 = QtWidgets.QLabel(Form)
        self.emailerror_2.setGeometry(QtCore.QRect(120, 190, 131, 25))
        self.emailerror_2.setObjectName("emailerror_2")
        self.emailerror_3 = QtWidgets.QLabel(Form)
        self.emailerror_3.setGeometry(QtCore.QRect(120, 270, 131, 25))
        self.emailerror_3.setObjectName("emailerror_3")
        self.emailerror_4 = QtWidgets.QLabel(Form)
        self.emailerror_4.setGeometry(QtCore.QRect(120, 350, 131, 25))
        self.emailerror_4.setObjectName("emailerror_4")
